name: Naweed
favicon: null
layout_spectrum: 0.10806024563498795
typography_spectrum: 0.40873682172968984
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6058366906363517
  lightness: 0.5361979035660625
  saturation: 0.03910406189970672
  rhythmicContrast: 0.4962209549266845
purpose: []
